#+TITLE: Poems 
#+SLUG: poe


* Unlike me yesterday
Unlike me yesterday

I woke up well today.
Woke up with hope today.
So I’ll work hard today,
Unlike me yesterday.

I drank brew well today.
Read my news feed today.
Said just one feed today
Unlike me yesterday.

I ate lunch well today.
Watched a short clip today.
Said just one clip today
Unlike me yesterday.

I ate tea well today.
Watched my sweet show today.
Said just one show today
Unlike me yesterday.

I told my lie today,
Said I’ll work hard today.
But I just lost my day,
Just like me yesterday.

* First love
My love
How strong you look, yet fragile.
Though you shaped so many,
You never sought acclaim.
But now, many loathe you,
And many more neglect you.

Yet I still love.
For if I love you only at your brightest,
Did I truly love at all?
I will not abandon you,
for you are my home,
my sanctuary,
my Britain.


“Saying the thing the reader already knows, is the deepest one can be — taking them to the place they know exists but don’t know how to get there.”
