#+title: Wedding Review

* Ceremony
The ceremony it self was straight forward, one of the registrars took us to a different room beforehand to do get the pronouciation of our names right. We used the speakers they had in the room connected to a phone and had some music planned. We had a pretty minimal ceremony, no readings just music for the procession, recession and some ambiant music as various signatures were scribbled. 

*  Plan
We originally wanted a very small family only wedding, so we planned just the ceremony and some afternoon tea with around 16 people. But then as we got closer to the wedding day we realised we wanted friends as well. Luckliy we chose a fairly large ceremony room so we could get more people in just for the ceremony.  However, the afternoon tea can only hold a maximum of 20 people so after the ceremony we had to dismiss our Friends for the tea, and then we met up with just our friends in Small Bar for the evening. 

* Charlotte
We discovered Charlotte while searching online for a Bristol-based photographer. We looked on her portfolio and saw that she had shots from the Christmas steps a location that was dear to us so we sent an email asking about our day and what we wanted. She sent us an offer which we accepted (informally). We then had a Zoom call to get to know each other and what we wanted, she was very friendly and just wanted to get know us a abit to better understand what we wanted and to put us at ease.

We wanted mostly candid moments of the day and some couple shots around the city, she had shot at all the locations we wanted so understod exactly what we wanted. We only needed half-day coverage to cover the morning from the Avon Gorge hotel to the afternon tea at Harbour Hotel. We had a rough idea of the timeline but she helped us structure it more and
from the start, everything felt straightforward and well organised on her side, from signing the contract to discussing timings and locations.

Since we didn’t have a wedding planner Charlotte was a brilliant source of guidance, she was helpful with questions regarding how the ceremony would unfold information we couldn't find on the website of the registry office. 

Close to the day we had a second zoom call to iron out final details so that everything flowed smoothly. During the day she blended into the background when appropriate to get the candid shots but was very accomodating of speicific shots some of the guests wanted.

Charlotte knew some fantastic photo spots around Bristol we have such lovely couple shots around the city thanks to her, including several that were special to us. She even stayed beyond her scheduled time to make sure we got a few extra shots, which we really appreciated.

Her communication was excellent throughout, and the turnaround time was rapid we received a sneak peeks within a couple of days and the full gallery just three weeks later. Charlotte is a lovely person to have with you on the day, and total professional! can't recommend her enough.

* Makeup by Macy
makeupbymacy.com

Macy did an amazing job on my hair and makeup! I came to her with a vision for my hair that I wasn’t even sure would be achievable, but she absolutely exceeded my expectations and I received so many compliments on the day. As someone who doesn’t usually wear much makeup, she completely nailed the subtle yet dressy look I wanted, and I felt so confident thanks to the excellent job she did.

I found Macy through an online search for makeup artists in Bristol and booked a trial at her studio. The trial was great, she really listened to what I wanted, offered helpful suggestions, and made sure I was completely happy with the look.


* Wedding

Some of our wedding guests stayed at the Avon Gorge by Hotel du Vin, we mostly picked due to proximity reasons but it turned out to be an ideal venue for pre ceremony photos. It has beautiful interiors and balcony with a great views of the gorge and the Clifton Suspension Bridge. 

Our ceremony took place at the Bristol Registry Office in the city centre, when we went for our notice giving and interview we were shown the inside of the room for the ceremony. We chose the crimson-walled “Red Room” (officially the Mayoral Room), and while I admit I was slightly taken aback by the bold colour at first, the light and setting of the room were beautiful and the photos turned out great. The two registrars involved were also very freindly and welcoming.  

Following the ceremony, we hosted our afternoon tea at the stylish Harbour Hotel right next to the registry office. The interioir is goergoesly decorated and the photos from there turned out so well. The staff were brilliant from start to finish. They were friendly, attentive, and incredibly accommodating, especially with a few dietary requirements in our group. Everything was well organised, and even though the space only seated around 20 people, it was ideal for our small gathering of family and close friends. The food was great, the scones were especially delicious, and everything felt freshly made and beautifully presented.


* Roots

Roots Floral Designs has always been a special place for us we used to live right next to it and it’s where I bought flowers for Zoë on our very first Valentine’s Day back in 2016, so it was natural to have them create our wedding flowers too.

They offer beautfully designed set arrangements at extremely affordable prices. To us custom arrangements was not important, only that it looked like the very first flowers I bought all those years ago. So we just picked the arrangement that matched the valentines flowers and the buttonholes and ordered online.  

In the week leading up to the wedding, I popped into the shop a couple of times just to check in, and the team were always super friendly and very reassuring. They don’t usually open on Saturdays, but since our wedding was that day, we collected the flowers on Friday evening. The florists gave us clear, practical instructions on how to keep everything fresh overnight and were so understanding about the timing. They even reassured us that if there were any issues the next morning, we could email and they’d come in early on Saturday to sort it!

The flowers looked absolutely beautiful on the day and were still perfectly fresh. It felt really special to have flowers and a design from the same place that’s been part of our story from the beginning. 

* Suit
I hired my wedding suit from Clifton Suits, a navy three-piece with a subtle tweed check, and was thoroughly impressed with both the quality and the service. From the initial fitting to the final collection, it was a smooth process.  A minor mix-up was resolved swiftly and without any fuss, which I greatly appreciated.

The suit fitted perfectly and was comfortable to wear throughout the day. I paired it with a navy trench coat from YMC, although the suit itself was more than warm enough.

I wore a pair of tan brogues by Loakes which I got from InStep in bristol. The husband and wife owners are also lovely people who were incredibly helpful, in factthe first pair the owner picked  was perfect, the man clealry knows his shoes. 

* Dress
For my wedding outfit, I wore the elegant Afra bustier gown from crafted from Solace London. It was made of soft crêpe and satin with a subtle back slit that added a touch of glamour. Over it, I layered a wool- wrap coat from the white company with an exaggerated shawl collar and detachable tie belt — warm, chic, and the perfect complement to the simplicity of the dress.

To complete the look, I wore Rachel Simpson ivory peep-toe shoes, delicately adorned with double bows. They were my dream shoes (a lucky find on eBay for £35) and they made me feel every bit as special as I’d hoped.
